name: sos_maison
description: "Application de gestion de services à domicile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  zego_uikit: ^2.28.11
  zego_uikit_prebuilt_call: ^4.16.27
  audioplayers: ^6.4.0
  zego_express_engine: ^3.20.0
  zego_uikit_signaling_plugin: ^2.8.11
  image_picker: ^1.1.2
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  logger: ^2.0.2
  url_launcher: ^6.1.14
  http: ^1.3.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.0
  google_sign_in: ^6.1.4
  flutter_web_auth: ^0.5.0
  provider: ^6.1.2
  firebase_core: ^3.13.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/2000.webp
    - assets/2001.jpg
    - assets/2002.jpg
    - assets/2003.jpg
    - assets/house1.webp
    - assets/house2.jpg
    - assets/house3.avif
    - assets/house4.jpeg
    - assets/garden.jpg
    - assets/gafs.jpg
    - assets/maison.avif
    - assets/clean.png
    - assets/brush_paint.png
    - assets/pincee.png
    - assets/plumb.jpg
    - assets/tools.png
    - assets/cleanni.png
    - assets/handym.jpg
    - assets/app_icon.png
    - assets/google.png
    - assets/facebook.png
    - assets/comment.png