// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-AHv-QBoIewY0dYfEHhsqfCs25wa6_M',
    appId: '1:529397669736:web:186143c2bd9260e1df40dd',
    messagingSenderId: '529397669736',
    projectId: 'zegocloud-27d09',
    authDomain: 'zegocloud-27d09.firebaseapp.com',
    storageBucket: 'zegocloud-27d09.firebasestorage.app',
    measurementId: 'G-Y1L6JF6ML6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsf_V-B-1XG0OX1lq42bn8hPDSU6Ckmg',
    appId: '1:529397669736:android:29335f7d5c9c75fddf40dd',
    messagingSenderId: '529397669736',
    projectId: 'zegocloud-27d09',
    storageBucket: 'zegocloud-27d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ykH_96NwaiXLVT-q-T2BA5q5OtmDL7U',
    appId: '1:529397669736:ios:2ec95f4e1218f53adf40dd',
    messagingSenderId: '529397669736',
    projectId: 'zegocloud-27d09',
    storageBucket: 'zegocloud-27d09.firebasestorage.app',
    iosBundleId: 'com.example.design',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ykH_96NwaiXLVT-q-T2BA5q5OtmDL7U',
    appId: '1:529397669736:ios:2ec95f4e1218f53adf40dd',
    messagingSenderId: '529397669736',
    projectId: 'zegocloud-27d09',
    storageBucket: 'zegocloud-27d09.firebasestorage.app',
    iosBundleId: 'com.example.design',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-AHv-QBoIewY0dYfEHhsqfCs25wa6_M',
    appId: '1:529397669736:web:7e40e394219e1488df40dd',
    messagingSenderId: '529397669736',
    projectId: 'zegocloud-27d09',
    authDomain: 'zegocloud-27d09.firebaseapp.com',
    storageBucket: 'zegocloud-27d09.firebasestorage.app',
    measurementId: 'G-SSK67GLGZ0',
  );
}
